"""Tiny JSON storage for conversations and append-only trajectories."""

# Import JSON to serialize Python dictionaries.
import json
# Import Path for operating-system-safe file paths.
from pathlib import Path

# Store generated data at the project root, independent of the source layout.
DATA_DIRECTORY = Path(__file__).parent.parent / "data"
# Give each session its own readable conversation file.
SESSIONS_DIRECTORY = DATA_DIRECTORY / "sessions"
# Append every completed turn to one event log.
TRAJECTORY_FILE = DATA_DIRECTORY / "trajectories.jsonl"
# Append privacy-bounded resume screening audits separately from chat turns.
RESUME_SCREENING_FILE = DATA_DIRECTORY / "resume_screening_runs.jsonl"
# Append outreach state transitions without storing message bodies.
OUTREACH_FILE = DATA_DIRECTORY / "outreach_runs.jsonl"
# Save resumable DAG runs separately from public conversation history.
WORKFLOWS_DIRECTORY = DATA_DIRECTORY / "workflows"


# Load one session's message history.
def load_session(session_id: str) -> list[dict]:
    """Return a session history, or an empty history for a new session."""
    # Build the session filename only from the UUID generated by our application.
    path = SESSIONS_DIRECTORY / f"{session_id}.json"
    # Start a new conversation when no saved file exists.
    if not path.exists():
        # Return a fresh list that the caller may safely modify.
        return []
    # Decode and return the saved JSON messages.
    return json.loads(path.read_text(encoding="utf-8"))


# Persist the current message history atomically enough for this learning project.
def save_session(session_id: str, messages: list[dict]) -> None:
    """Save all public user, assistant, and tool messages for a session."""
    # Create parent directories on the first run.
    SESSIONS_DIRECTORY.mkdir(parents=True, exist_ok=True)
    # Select this session's destination file.
    path = SESSIONS_DIRECTORY / f"{session_id}.json"
    # Write indented UTF-8 JSON so a learner can inspect it easily.
    path.write_text(json.dumps(messages, indent=2, ensure_ascii=False), encoding="utf-8")


# Append one complete turn trajectory without rewriting previous traces.
def append_trajectory(trajectory: dict) -> None:
    """Append one trajectory as a single JSON Lines record."""
    # Create the data folder if this is the first agent turn.
    DATA_DIRECTORY.mkdir(parents=True, exist_ok=True)
    # Open in append mode so earlier execution evidence remains intact.
    with TRAJECTORY_FILE.open("a", encoding="utf-8") as file:
        # Store one compact JSON object per line for easy streaming later.
        file.write(json.dumps(trajectory, ensure_ascii=False) + "\n")


def append_resume_screening_run(run: dict) -> None:
    """Persist metrics and events without duplicating candidate result rows."""
    DATA_DIRECTORY.mkdir(parents=True, exist_ok=True)
    safe_run = {key: value for key, value in run.items() if key != "results"}
    with RESUME_SCREENING_FILE.open("a", encoding="utf-8") as file:
        file.write(json.dumps(safe_run, ensure_ascii=False) + "\n")


def append_outreach_run(run: dict) -> None:
    """Append metadata-only outreach events."""
    DATA_DIRECTORY.mkdir(parents=True, exist_ok=True)
    with OUTREACH_FILE.open("a", encoding="utf-8") as file:
        file.write(json.dumps(run, ensure_ascii=False) + "\n")


def save_workflow_run(run: dict) -> None:
    """Persist one complete or paused workflow as readable JSON."""
    WORKFLOWS_DIRECTORY.mkdir(parents=True, exist_ok=True)
    path = WORKFLOWS_DIRECTORY / f"{run['run_id']}.json"
    temporary = path.with_suffix(".tmp")
    temporary.write_text(json.dumps(run, indent=2, ensure_ascii=False), encoding="utf-8")
    temporary.replace(path)


def load_workflow_run(run_id: str) -> dict:
    """Load a previously persisted workflow dictionary."""
    path = WORKFLOWS_DIRECTORY / f"{run_id}.json"
    if not path.exists():
        raise ValueError(f"Unknown workflow run: {run_id}")
    return json.loads(path.read_text(encoding="utf-8"))
