"""Tiny JSON storage for conversations and append-only trajectories."""

# Import JSON to serialize Python dictionaries.
import json
# Import Path for operating-system-safe file paths.
from pathlib import Path

# Store generated data at the project root, independent of the source layout.
DATA_DIRECTORY = Path(__file__).parent.parent / "data"
# Give each session its own readable conversation file.
SESSIONS_DIRECTORY = DATA_DIRECTORY / "sessions"
# Append every completed turn to one event log.
TRAJECTORY_FILE = DATA_DIRECTORY / "trajectories.jsonl"


# Load one session's message history.
def load_session(session_id: str) -> list[dict]:
    """Return a session history, or an empty history for a new session."""
    # Build the session filename only from the UUID generated by our application.
    path = SESSIONS_DIRECTORY / f"{session_id}.json"
    # Start a new conversation when no saved file exists.
    if not path.exists():
        # Return a fresh list that the caller may safely modify.
        return []
    # Decode and return the saved JSON messages.
    return json.loads(path.read_text(encoding="utf-8"))


# Persist the current message history atomically enough for this learning project.
def save_session(session_id: str, messages: list[dict]) -> None:
    """Save all public user, assistant, and tool messages for a session."""
    # Create parent directories on the first run.
    SESSIONS_DIRECTORY.mkdir(parents=True, exist_ok=True)
    # Select this session's destination file.
    path = SESSIONS_DIRECTORY / f"{session_id}.json"
    # Write indented UTF-8 JSON so a learner can inspect it easily.
    path.write_text(json.dumps(messages, indent=2, ensure_ascii=False), encoding="utf-8")


# Append one complete turn trajectory without rewriting previous traces.
def append_trajectory(trajectory: dict) -> None:
    """Append one trajectory as a single JSON Lines record."""
    # Create the data folder if this is the first agent turn.
    DATA_DIRECTORY.mkdir(parents=True, exist_ok=True)
    # Open in append mode so earlier execution evidence remains intact.
    with TRAJECTORY_FILE.open("a", encoding="utf-8") as file:
        # Store one compact JSON object per line for easy streaming later.
        file.write(json.dumps(trajectory, ensure_ascii=False) + "\n")
